# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a41d4e797b0948290f9589e99de2f64a08510e150187e2f32fdd332b628809b37c658efea62df44752a9f91f9dbe61ffa64030b5593fab1361abd1d1e9f81827

test:
  secret_key_base: b484ce0ca0c3eafc2b021e97f9f231f6229c7b6e279c73fda8d85f4494c2aebf272f279f2ad16ece3c0deccab4a92d69965e4423d081366de5a934133ea99ca0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
